name: SpawnerSuppression
version: 1
description: Limit entity spawn rate caused from spawner blocks
author: ame94
main: ca.ame94.SpawnerSuppression.PluginMain

commands:
    spawnersuppression:
        description: Modify plugin settings
        permission: spawnersuppression.admin
        permission-message: ยง4You are not permitted to use this plugin.
